version: '3.8'

services:
  chat_server:
    image: signal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
      - "4446:443"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_dev:/data/db   # Mount a named volume for MongoDB data
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  mongodb_data_dev:   # Define a named volume for MongoDB data
