version: '3.8'

services:
  chat_server:
    image: signal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "4443:443"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db   # Mount a named volume for MongoDB data
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_cloud
      MONGO_INITDB_ROOT_PASSWORD: 2BU9TSUeYCVZ


networks:
  mynetwork:

volumes:
  mongodb_data:   # Define a named volume for MongoDB data
