version: '3.8'

services:
  chat_server:
    image: signal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
