version: '3.8'

services:
  chat_server_dev:
    image: signal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
      - "4446:443"
    depends_on:
      - mongodb_dev
    networks:
      - mynetwork_dev

  mongodb_dev:
    image: mongo:latest
    volumes:
      - mongodb_data_dev:/dev_data/db   # Mount a named volume for MongoDB data
    networks:
      - mynetwork_dev


networks:
  mynetwork_dev:

volumes:
  mongodb_data_dev:   # Define a named volume for MongoDB data
